# Describes the format for available switch services

au190_fc:
  description: Implementing the Smart MQTT switch
  fields:
    entity_id:
      description: Name of entity.
      example: 'switch.living_room'